version : 1.0.{build}

before_build:
  cmd:
    cd AutoYoutube.Core

    nuget restore

    cd ../AutoYoutube

    nuget restore

environment:
  matrix:
    - solution_name: AutoYoutube.Core/AutoYoutube.Core.sln
    - solution_name: AutoYoutube/CommentAutomatic.sln

matrix:
  fast_finish: true

  - cmd: echo Hello
  solution_name: AutoYoutube.Core/AutoYoutube.Core.sln

build:
  project: $(solution_name)
  verbosity: normal

