version : 1.0.{build}

before_build:
  cmd:
    cd AutoYoutube


    nuget restore

matrix:
  fast_finish: true

build:
  project: AutoYoutube/CommentAutomatic.sln
  verbosity: normal

after_build:
  cmd:
    cp *.txt bin/Debug/

    7z a release.zip bin/Debug

artifacts:
  - path: AutoYoutube/release.zip
    name: release


deploy:
  release: AutomaticYoutubeCommend
  description: 'Newest release from Vo Ngoc Khang APPVEYOR_REPO_COMMIT_MESSAGE'
  artifact: release
  provider: GitHub
  auth_token:
    secure: nBAymlOEj7JNWuTrPuMzvTcgRPNhbQ03QoL9XkNZNaHHWsxC92dsAinHTsjTc1DH
  force_update: true
  on:
    branch: main