version : 1.0.{build}

before_build:
  cmd:
    cd AutoYoutube

    nuget restore

matrix:
  fast_finish: true

build:
  project: AutoYoutube/CommentAutomatic.sln
  verbosity: normal

after_build:
  cmd:
    7z a release.zip bin/Debug

artifacts:
  - path: AutoYoutube/release.zip
    name: release